baseURL = "https://emma-herve.netlify.com/"
languageCode = "fr-fr"
languageLang = "fr"
defaultContentLanguage = "fr"
title = "Emma Hervé"
theme = "emmaherve"
googleAnalytics = ""
disableLiveReload = false
disableKinds = ["RSS","taxonomy", "taxonomyTerm"]
relativeURLs = true
staticDir = "static"
enableRobotsTXT = true

[languages]
  [languages.fr]
    languageName = "Français"
    languageCode = "fr-fr"
    languageLang = "fr"
    weight = 1
    contentDir = "content"

[params]
  description = "Cabinet d'Ostéopathie Paris 15ème"
  homeTitle = " - Le meilleur des kakapos"
  facebookUrl = "https://www.facebook.com/OsteopathieEmmaHerve"
  og_image = "images/sharing-visual.jpg"
  mail = "emmaosteo@gmail.com"
  address = "12 Rue Ferdinand Fabre, 75015 Paris"
  mapsUrl = "https://www.google.com/maps/place/Emma+Herv%C3%A9/@48.8384865,2.2945037,17z/data=!3m1!4b1!4m5!3m4!1s0x47e670156b2b918f:0x361fcdc45366b4cb!8m2!3d48.838483!4d2.2966924"
  tel = "06 30 87 41 95"
  doctoUrl = "https://www.doctolib.fr/osteopathe/paris/emma-herve"
  doctotxt = "Prendre rdv sur doctolib"
  notice = "INFOS CORONAVIRUS : Le cabinet est ouvert, pour connaître notre fonctionnement c’est par ici : Consulter ma page Doctolib"

[menu]
  [[menu.main]]
    name = "L’ostéopathie"
    url = "/osteopathie/osteopathie"
    weight = 1

  [[menu.main]]
    name = "Mon ostéo"
    url = "/emma-herve/emma-herve"
    weight = 2

  [[menu.main]]
  name = "Contact et tarifs"
  url = "/contact-tarifs/contact-tarifs"
  weight = 3
  
  [[menu.main]]
  name = "Le Mag"
  url = "/article"
  weight = 4

[markup.goldmark.renderer] 
unsafe= true